#! /bin/bash
yum update -y
yum install -y httpd
yum install git -y
systemctl start httpd
systemctl enable httpd
git clone https://github.com/techproedu/designer.git
cd /designer
chmod -R 777 /var/www/html
cp -R . /var/www/html
systemctl restart httpd
